-- Portuguese Constitution Plays Pokemon
-- DeSmuME Lua Script - Direct Emulator Control
-- Generated by GameScript-PDF-to-Game-Inputs-Converter

-- ============================================================
-- CONFIGURATION
-- ============================================================

local CONFIG = {
    INPUT_FILE = "game_inputs.txt",
    FRAMES_PER_INPUT = 9,  -- ~6.67 inputs per second at 60fps
    PROGRESS_INTERVAL = 100  -- Update progress every N inputs
}

-- ============================================================
-- STATE VARIABLES
-- ============================================================

local state = {
    inputsLoaded = false,
    inputs = {},
    currentFrame = 0,
    inputIndex = 1,
    totalInputs = 0,
    lastProgress = 0,
    startTime = nil
}

-- ============================================================
-- BUTTON MAPPING
-- ============================================================

local function getButtonPress(button)
    -- Map button name to DeSmuME joypad input table
    local buttons = {
        UP = {up=true},
        DOWN = {down=true},
        LEFT = {left=true},
        RIGHT = {right=true},
        A = {A=true},
        B = {B=true},
        START = {start=true},
        SELECT = {select=true},
        L = {L=true},
        R = {R=true},
        X = {X=true},
        Y = {Y=true},
        NO_INPUT = {}
    }
    return buttons[button] or {}
end

-- ============================================================
-- INPUT LOADING
-- ============================================================

local function loadInputs()
    -- Load button sequence from text file
    if state.inputsLoaded then 
        return true 
    end
    
    -- Attempt to open input file
    local file = io.open(CONFIG.INPUT_FILE, "r")
    if not file then
        print("ERROR: Could not open " .. CONFIG.INPUT_FILE)
        print("Ensure the file is in the same directory as DeSmuME executable")
        return false
    end
    
    -- Read inputs line by line
    for line in file:lines() do
        local trimmed = line:gsub("^%%s*(.-)%%s*$", "%%1")
        if trimmed ~= "" then
            table.insert(state.inputs, trimmed)
        end
    end
    file:close()
    
    state.totalInputs = #state.inputs
    state.inputsLoaded = true
    
    -- Display initialization information
    print("============================================================")
    print("PORTUGUESE CONSTITUTION PLAYS POKEMON")
    print("============================================================")
    print(string.format("Document: Portuguese Constitution"))
    print(string.format("Total inputs loaded: %s", 
        string.format("%d", state.totalInputs):reverse():gsub("(%%d%%d%%d)", "%%1,"):reverse():gsub("^,", "")))
    print(string.format("Estimated duration: %.1f minutes (%.1f hours)", 
        529.8375, 8.830625))
    print("============================================================")
    print("")
    
    return true
end

-- ============================================================
-- PROGRESS DISPLAY
-- ============================================================

local function displayProgress()
    -- Display current progress with timing information
    local percent = (state.inputIndex / state.totalInputs) * 100
    local elapsed = os.difftime(os.time(), state.startTime)
    local estimated_total = (elapsed / state.inputIndex) * state.totalInputs
    local remaining = estimated_total - elapsed
    
    print(string.format("Progress: %d/%d (%.1f%%) | Elapsed: %.1fm | ETA: %.1fm", 
        state.inputIndex, state.totalInputs, percent, elapsed/60, remaining/60))
end

local function displayCompletion()
    -- Display completion summary
    local totalTime = os.difftime(os.time(), state.startTime)
    
    print("")
    print("============================================================")
    print("PORTUGUESE CONSTITUTION HAS CONCLUDED")
    print("============================================================")
    print(string.format("Total inputs executed: %d", state.totalInputs))
    print(string.format("Total time: %.1f minutes (%.1f hours)", 
        totalTime/60, totalTime/3600))
    print("Portuguese Constitution rests.")
    print("============================================================")
end

-- ============================================================
-- MAIN EXECUTION
-- ============================================================

-- Initialize: Load inputs from file
if not loadInputs() then
    print("Failed to load inputs. Script terminated.")
    return
end

print("Portuguese Constitution begins its Pokemon journey...")
print("")

state.startTime = os.time()

-- Main loop: Process inputs frame by frame
while true do
    -- Check if it's time to send next input
    if state.currentFrame % CONFIG.FRAMES_PER_INPUT == 0 then
        if state.inputIndex <= state.totalInputs then
            -- Send current input to emulator
            local button = state.inputs[state.inputIndex]
            joypad.set(1, getButtonPress(button))
            
            -- Display progress at intervals
            if state.inputIndex % CONFIG.PROGRESS_INTERVAL == 0 
               and state.inputIndex ~= state.lastProgress then
                displayProgress()
                state.lastProgress = state.inputIndex
            end
            
            state.inputIndex = state.inputIndex + 1
        else
            -- All inputs processed - display completion and exit
            displayCompletion()
            break
        end
    end
    
    state.currentFrame = state.currentFrame + 1
    emu.frameadvance()
end
