"""
JSON to DeSmuME Lua Converter

Converts JSON game input sequences into Lua scripts for DeSmuME emulator automation.
Allows any text document to "play" a video game through deterministic button inputs.

This script generates two files:
1. A text file containing the button sequence
2. A Lua script that feeds these inputs to DeSmuME frame-by-frame

Author: Ricardo Martins
Repository: https://github.com/RiGraMa/GameScript-PDF-to-Game-Inputs-Converter
"""

import json
import argparse
import sys
from pathlib import Path


def get_lua_script_template(document_name="Document", total_inputs=0):
    """
    Generate DeSmuME Lua script with custom document name and timing estimates.
    
    The generated Lua script:
    - Loads button inputs from a text file
    - Sends inputs to the emulator frame-by-frame
    - Displays progress updates during execution
    - Tracks elapsed time and estimates remaining time
    
    Args:
        document_name (str): Name of source document (displayed in progress)
        total_inputs (int): Total number of inputs (for time estimation)
        
    Returns:
        str: Complete Lua script as a string
    """
    # Calculate estimated duration (9 frames per input at 60fps)
    estimated_minutes = (total_inputs * 9) / 60 / 60
    
    # Format document name for display
    doc_name_upper = document_name.upper()
    doc_name_display = document_name
    
    return f'''-- {document_name} Plays Pokemon
-- DeSmuME Lua Script - Direct Emulator Control
-- Generated by GameScript-PDF-to-Game-Inputs-Converter

-- ============================================================
-- CONFIGURATION
-- ============================================================

local CONFIG = {{
    INPUT_FILE = "game_inputs.txt",
    FRAMES_PER_INPUT = 9,  -- ~6.67 inputs per second at 60fps
    PROGRESS_INTERVAL = 100  -- Update progress every N inputs
}}

-- ============================================================
-- STATE VARIABLES
-- ============================================================

local state = {{
    inputsLoaded = false,
    inputs = {{}},
    currentFrame = 0,
    inputIndex = 1,
    totalInputs = 0,
    lastProgress = 0,
    startTime = nil
}}

-- ============================================================
-- BUTTON MAPPING
-- ============================================================

local function getButtonPress(button)
    -- Map button name to DeSmuME joypad input table
    local buttons = {{
        UP = {{up=true}},
        DOWN = {{down=true}},
        LEFT = {{left=true}},
        RIGHT = {{right=true}},
        A = {{A=true}},
        B = {{B=true}},
        START = {{start=true}},
        SELECT = {{select=true}},
        L = {{L=true}},
        R = {{R=true}},
        X = {{X=true}},
        Y = {{Y=true}},
        NO_INPUT = {{}}
    }}
    return buttons[button] or {{}}
end

-- ============================================================
-- INPUT LOADING
-- ============================================================

local function loadInputs()
    -- Load button sequence from text file
    if state.inputsLoaded then 
        return true 
    end
    
    -- Attempt to open input file
    local file = io.open(CONFIG.INPUT_FILE, "r")
    if not file then
        print("ERROR: Could not open " .. CONFIG.INPUT_FILE)
        print("Ensure the file is in the same directory as DeSmuME executable")
        return false
    end
    
    -- Read inputs line by line
    for line in file:lines() do
        local trimmed = line:gsub("^%%s*(.-)%%s*$", "%%1")
        if trimmed ~= "" then
            table.insert(state.inputs, trimmed)
        end
    end
    file:close()
    
    state.totalInputs = #state.inputs
    state.inputsLoaded = true
    
    -- Display initialization information
    print("============================================================")
    print("{doc_name_upper} PLAYS POKEMON")
    print("============================================================")
    print(string.format("Document: {doc_name_display}"))
    print(string.format("Total inputs loaded: %s", 
        string.format("%d", state.totalInputs):reverse():gsub("(%%d%%d%%d)", "%%1,"):reverse():gsub("^,", "")))
    print(string.format("Estimated duration: %.1f minutes (%.1f hours)", 
        {estimated_minutes}, {estimated_minutes/60}))
    print("============================================================")
    print("")
    
    return true
end

-- ============================================================
-- PROGRESS DISPLAY
-- ============================================================

local function displayProgress()
    -- Display current progress with timing information
    local percent = (state.inputIndex / state.totalInputs) * 100
    local elapsed = os.difftime(os.time(), state.startTime)
    local estimated_total = (elapsed / state.inputIndex) * state.totalInputs
    local remaining = estimated_total - elapsed
    
    print(string.format("Progress: %d/%d (%.1f%%) | Elapsed: %.1fm | ETA: %.1fm", 
        state.inputIndex, state.totalInputs, percent, elapsed/60, remaining/60))
end

local function displayCompletion()
    -- Display completion summary
    local totalTime = os.difftime(os.time(), state.startTime)
    
    print("")
    print("============================================================")
    print("{doc_name_upper} HAS CONCLUDED")
    print("============================================================")
    print(string.format("Total inputs executed: %d", state.totalInputs))
    print(string.format("Total time: %.1f minutes (%.1f hours)", 
        totalTime/60, totalTime/3600))
    print("{doc_name_display} rests.")
    print("============================================================")
end

-- ============================================================
-- MAIN EXECUTION
-- ============================================================

-- Initialize: Load inputs from file
if not loadInputs() then
    print("Failed to load inputs. Script terminated.")
    return
end

print("{doc_name_display} begins its Pokemon journey...")
print("")

state.startTime = os.time()

-- Main loop: Process inputs frame by frame
while true do
    -- Check if it's time to send next input
    if state.currentFrame % CONFIG.FRAMES_PER_INPUT == 0 then
        if state.inputIndex <= state.totalInputs then
            -- Send current input to emulator
            local button = state.inputs[state.inputIndex]
            joypad.set(1, getButtonPress(button))
            
            -- Display progress at intervals
            if state.inputIndex % CONFIG.PROGRESS_INTERVAL == 0 
               and state.inputIndex ~= state.lastProgress then
                displayProgress()
                state.lastProgress = state.inputIndex
            end
            
            state.inputIndex = state.inputIndex + 1
        else
            -- All inputs processed - display completion and exit
            displayCompletion()
            break
        end
    end
    
    state.currentFrame = state.currentFrame + 1
    emu.frameadvance()
end
'''


def convert_json_to_lua_format(json_file, output_file="game_inputs.txt"):
    """
    Convert JSON input array to plain text format for Lua script.
    
    Reads a JSON file containing an array of button names and writes
    them to a text file (one button per line) that can be read by
    the Lua script.
    
    Args:
        json_file (str): Path to JSON file with input sequence
        output_file (str): Path for output text file
        
    Returns:
        int: Number of inputs converted (0 if failed)
        
    Example:
        >>> convert_json_to_lua_format("inputs.json", "buttons.txt")
        23451
    """
    try:
        json_path = Path(json_file)
        
        # Validate input file exists
        if not json_path.exists():
            print(f"[ERROR] File not found: {json_file}")
            return 0
        
        # Load and validate JSON
        with open(json_path, 'r', encoding='utf-8') as f:
            inputs = json.load(f)
        
        if not inputs:
            print(f"[ERROR] No inputs found in {json_file}")
            return 0
        
        if not isinstance(inputs, list):
            print(f"[ERROR] JSON must contain an array of button names")
            return 0
        
        # Write to text file (one input per line)
        output_path = Path(output_file)
        with open(output_path, 'w', encoding='utf-8') as f:
            for inp in inputs:
                f.write(str(inp) + '\n')
        
        print(f"[SUCCESS] Converted {len(inputs):,} inputs")
        print(f"[OUTPUT] {output_file}")
        return len(inputs)
    
    except json.JSONDecodeError as e:
        print(f"[ERROR] Invalid JSON in {json_file}")
        print(f"        Details: {e}")
        return 0
    except Exception as e:
        print(f"[ERROR] {e}")
        return 0


def generate_lua_script(document_name, total_inputs, output_file="document_player.lua"):
    """
    Generate DeSmuME Lua automation script.
    
    Creates a complete Lua script that can be loaded in DeSmuME's
    Lua scripting window to automate button inputs.
    
    Args:
        document_name (str): Name of source document
        total_inputs (int): Total number of inputs (for estimates)
        output_file (str): Path for output Lua file
        
    Returns:
        bool: True if successful, False otherwise
    """
    try:
        script_content = get_lua_script_template(document_name, total_inputs)
        
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(script_content)
            
        print(f"[SUCCESS] Generated Lua script: {output_file}")
        return True
        
    except Exception as e:
        print(f"[ERROR] Failed to create Lua script: {e}")
        return False


def get_document_name_from_user(json_filename):
    """
    Prompt user for document name with intelligent suggestion.
    
    Suggests a name based on the JSON filename, allowing user to
    accept the suggestion (press Enter) or provide custom name.
    
    Args:
        json_filename (str): Input JSON filename
        
    Returns:
        str: Document name (from user or suggested)
        
    Example:
        >>> get_document_name_from_user("my_thesis_2024.json")
        # Suggests: "My Thesis 2024"
        # User can accept or type custom name
    """
    # Generate suggestion from filename
    suggested_name = (
        Path(json_filename)
        .stem
        .replace('_', ' ')
        .replace('-', ' ')
        .title()
    )
    
    print("\nDocument Identification")
    print("-" * 60)
    print(f"Suggested name: {suggested_name}")
    print("(Press Enter to accept, or type custom name)")
    print()
    
    user_input = input("Document name: ").strip()
    
    return user_input if user_input else suggested_name


def display_conversion_summary(document_name, num_inputs, txt_output, lua_output):
    """
    Display formatted summary of conversion results.
    
    Args:
        document_name (str): Name of source document
        num_inputs (int): Total inputs converted
        txt_output (str): Text file path
        lua_output (str): Lua script path
    """
    estimated_minutes = (num_inputs * 9) / 60 / 60
    
    print()
    print("=" * 60)
    print("CONVERSION COMPLETE")
    print("=" * 60)
    print()
    print(f"Document:           {document_name}")
    print(f"Total inputs:       {num_inputs:,}")
    print(f"Estimated duration: {estimated_minutes:.1f} minutes "
          f"({estimated_minutes/60:.1f} hours)")
    print()
    print("Generated files:")
    print(f"  1. {txt_output} (input data)")
    print(f"  2. {lua_output} (DeSmuME script)")
    print()
    print("Usage Instructions:")
    print("  1. Copy both files to DeSmuME directory")
    print("  2. Open DeSmuME and load Pokemon ROM")
    print("  3. Tools -> Lua Scripting -> New Lua Script Window")
    print(f"  4. Load {lua_output}")
    print(f"  5. Watch '{document_name}' play Pokemon!")
    print()
    print("Note: Progress updates appear every 100 inputs")
    print("=" * 60)


def main():
    """
    Main entry point for JSON to Lua conversion.
    
    Handles command-line arguments, user interaction, and orchestrates
    the conversion process from JSON inputs to DeSmuME-compatible files.
    """
    # Configure argument parser
    parser = argparse.ArgumentParser(
        description="Convert JSON game inputs to DeSmuME Lua automation script",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  Interactive mode (prompts for document name):
    python %(prog)s inputs.json
  
  Specify document name via command line:
    python %(prog)s thesis.json --name "My Friend's Thesis"
  
  Custom output file names:
    python %(prog)s data.json --name "Constitution" 
                              --txt-output inputs.txt 
                              --lua-output player.lua

Output Files:
  1. Text file: Button sequence (one per line)
  2. Lua file:  DeSmuME automation script

DeSmuME Usage:
  Load the Lua script via Tools -> Lua Scripting
  The script automatically reads the text file and sends inputs to emulator
        """
    )
    
    parser.add_argument(
        "json_file",
        help="JSON file containing button input sequence"
    )
    
    parser.add_argument(
        "--name",
        default=None,
        help='Document name (e.g., "My Thesis", "Constitution")'
    )
    
    parser.add_argument(
        "--txt-output",
        default="game_inputs.txt",
        help="Output text file for button sequence (default: game_inputs.txt)"
    )
    
    parser.add_argument(
        "--lua-output",
        default="document_player.lua",
        help="Output Lua script file (default: document_player.lua)"
    )
    
    args = parser.parse_args()
    
    # Get document name (from argument or user prompt)
    if args.name:
        document_name = args.name
    else:
        document_name = get_document_name_from_user(args.json_file)
    
    # Display conversion header
    print()
    print("=" * 60)
    print(f"{document_name.upper()} -> DESMUME LUA CONVERTER")
    print("=" * 60)
    print()
    
    # Step 1: Convert JSON to text format
    num_inputs = convert_json_to_lua_format(args.json_file, args.txt_output)
    
    if num_inputs == 0:
        print()
        print("[FAILED] Conversion aborted")
        return 1
    
    # Step 2: Generate Lua script
    if not generate_lua_script(document_name, num_inputs, args.lua_output):
        return 1
    
    # Display summary
    display_conversion_summary(
        document_name,
        num_inputs,
        args.txt_output,
        args.lua_output
    )
    
    return 0


if __name__ == "__main__":
    sys.exit(main())